export const FN_ID = {
  FN_DRAG_EL_CHEMOTION: 'FN_DRAG_EL_CHEMOTION',
  FN_CONTRIBUTE_TEMPLATE: 'FN_CONTRIBUTE_TEMPLATE',
  FN_DIFF: 'FN_DIFF',
  FN_TABLE_EXPORT: 'FN_TABLE_EXPORT',
  FN_SIZE_GRID: 'FN_SIZE_GRID',
};

export const FN = {
  [FN_ID.FN_DRAG_EL_CHEMOTION]: true,
  [FN_ID.FN_CONTRIBUTE_TEMPLATE]: true,
  [FN_ID.FN_DIFF]: false,
  [FN_ID.FN_TABLE_EXPORT]: true,
  [FN_ID.FN_SIZE_GRID]: true,
};
