import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faAnglesDown,
  faAnglesUp,
  faArrowsAlt,
  faArrowDown,
  faArrowRight,
  faArrowRightToBracket,
  faArrowsRotate,
  faArrowUp,
  faArrowUpRightFromSquare,
  faArrowsLeftRight,
  faArrowsUpDownLeftRight,
  faBan,
  faBars,
  faBookOpen,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faCaretUp,
  faChartDiagram,
  faCheck,
  faChevronDown,
  faChevronUp,
  faCircleArrowRight,
  faCircleCheck,
  faCircleInfo,
  faCirclePlus,
  faClockRotateLeft,
  faDiagramProject,
  faDownLeftAndUpRightToCenter,
  faDownload,
  faEllipsis,
  faEllipsisVertical,
  faExclamationCircle,
  faEye,
  faFlask,
  faFileExport,
  faFileImport,
  faFileLines,
  faFileWord,
  faGears,
  faGlobe,
  faGripLinesVertical,
  faLayerGroup,
  faLink,
  faList,
  faMagnifyingGlass,
  faMinus,
  faObjectGroup,
  faPaintbrush,
  faPaperclip,
  faPaperPlane,
  faPencil,
  faPlus,
  faReply,
  faRotate,
  faSpellCheck,
  faSpinner,
  faSquare,
  faT,
  faTag,
  faTableCells,
  faTableCellsLarge,
  faTimes,
  faTriangleExclamation,
  faUpRightAndDownLeftFromCenter,
} from '@fortawesome/free-solid-svg-icons';
import {
  faClock,
  faClone,
  faCircleQuestion,
  faFloppyDisk,
  faPaste,
  faSquareCaretDown,
  faTrashCan,
} from '@fortawesome/free-regular-svg-icons';

const icons = {
  faAnglesDown,
  faAnglesUp,
  faArrowsAlt,
  faArrowDown,
  faArrowRight,
  faArrowRightToBracket,
  faArrowsRotate,
  faArrowUp,
  faArrowUpRightFromSquare,
  faArrowsLeftRight,
  faArrowsUpDownLeftRight,
  faBan,
  faBars,
  faBookOpen,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faCaretUp,
  faChartDiagram,
  faCheck,
  faChevronDown,
  faChevronUp,
  faClock,
  faClockRotateLeft,
  faCircleArrowRight,
  faCircleCheck,
  faCircleInfo,
  faCirclePlus,
  faCircleQuestion,
  faClone,
  faDiagramProject,
  faDownLeftAndUpRightToCenter,
  faDownload,
  faEllipsis,
  faEllipsisVertical,
  faExclamationCircle,
  faEye,
  faFlask,
  faFileExport,
  faFileImport,
  faFileLines,
  faFileWord,
  faFloppyDisk,
  faGears,
  faGlobe,
  faGripLinesVertical,
  faLayerGroup,
  faLink,
  faList,
  faMagnifyingGlass,
  faMinus,
  faObjectGroup,
  faPaintbrush,
  faPaperclip,
  faPaperPlane,
  faPaste,
  faPencil,
  faPlus,
  faReply,
  faRotate,
  faSpellCheck,
  faSquare,
  faSquareCaretDown,
  faT,
  faTag,
  faTableCells,
  faTableCellsLarge,
  faTimes,
  faTrashCan,
  faTriangleExclamation,
  faUpRightAndDownLeftFromCenter,
};

const iconAnimated = {
  faSpinner,
};

// Main icons object
const iconsObject = Object.freeze(
  Object.fromEntries(
    Object.entries(icons).map(([key, value]) => [
      key,
      // eslint-disable-next-line react/jsx-key
      <FontAwesomeIcon icon={value} />,
    ]),
  ),
);

// Animated icons object
const animatedIconsObject = Object.freeze(
  Object.fromEntries(
    Object.entries(iconAnimated).map(([key, value]) => [
      key,
      // eslint-disable-next-line react/jsx-key
      <FontAwesomeIcon icon={value} spin />,
    ]),
  ),
);

// Final export
export default {
  ...iconsObject,
  ...animatedIconsObject,
};
