# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "*" ]
  # pull_request:
  #   branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - name: Configure Git and NPM
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        # Set new configs
        git config --global url."https:///cllde8:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"

        # Configure yarn
        {
          echo "registry=https://registry.npmjs.org/"
          echo "always-auth=true"
          echo "@cllde8:registry=https://npm.pkg.github.com"
          echo "//npm.pkg.github.com/:_authToken=${GH_TOKEN}"
        } > ~/.npmrc

    - name: Install dependencies
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: yarn install --frozen-lockfile --network-timeout 300000

    - name: Build
      run: yarn run build

    - name: Test
      run: yarn test
